// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DiscoverApps() {
  return window['go']['main']['App']['DiscoverApps']();
}

export function FrontendReady() {
  return window['go']['main']['App']['FrontendReady']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function KillProcess(arg1) {
  return window['go']['main']['App']['KillProcess'](arg1);
}

export function Log(arg1) {
  return window['go']['main']['App']['Log'](arg1);
}

export function OpenConfigInEditor() {
  return window['go']['main']['App']['OpenConfigInEditor']();
}

export function ResolveIcon(arg1) {
  return window['go']['main']['App']['ResolveIcon'](arg1);
}

export function SetTargetApp(arg1) {
  return window['go']['main']['App']['SetTargetApp'](arg1);
}

export function SetTickInterval(arg1) {
  return window['go']['main']['App']['SetTickInterval'](arg1);
}

export function Snapshot() {
  return window['go']['main']['App']['Snapshot']();
}

export function WindowGetSize() {
  return window['go']['main']['App']['WindowGetSize']();
}

export function WindowSetMaxSize(arg1, arg2) {
  return window['go']['main']['App']['WindowSetMaxSize'](arg1, arg2);
}

export function WindowSetMinSize(arg1, arg2) {
  return window['go']['main']['App']['WindowSetMinSize'](arg1, arg2);
}

export function WindowSetSize(arg1, arg2) {
  return window['go']['main']['App']['WindowSetSize'](arg1, arg2);
}
