// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {process} from '../models';
import {main} from '../models';

export function DiscoverApps():Promise<Array<process.DiscoveredApp>>;

export function GetAppVersion():Promise<string>;

export function GetConfig():Promise<main.ConfigState>;

export function GetPrivateIcons():Promise<Record<string, string>>;

export function KillProcess(arg1:number):Promise<process.KillResult>;

export function Log(arg1:string):Promise<void>;

export function OpenConfigInEditor():Promise<void>;

export function SetTargetApp(arg1:string):Promise<void>;

export function SetTickInterval(arg1:number):Promise<void>;

export function Snapshot():Promise<process.ProcessSnapshot>;

export function WindowGetSize():Promise<any>;

export function WindowSetSize(arg1:number,arg2:number):Promise<void>;
